baseURL = "//ziglang.org/"
languageCode = "en-us"
theme = "ziglang-original"
disableKinds = ["taxonomy", "term"]
timeout = 1000000

[params]
disable_zig_rendering = false
zig_code_basepath = "assets/zig-code/"
downloads_release_order = [
  "master",
  "0.9.1",
  "0.9.0",
  "0.8.1",
  "0.8.0",
  "0.7.1",
  "0.7.0",
  "0.6.0",
  "0.5.0",
  "0.4.0",
  "0.3.0",
  "0.2.0",
  "0.1.1",
]
downloads_arch_order = [
  "src",
  "bootstrap",
  "x86_64-linux",
  "i386-linux",
  "riscv64-linux",
  "aarch64-linux",
  "armv7a-linux",
  "armv6kz-linux",
  "x86_64-macos",
  "aarch64-macos",
  "x86_64-windows",
  "i386-windows",
  "aarch64-windows",
  "x86_64-freebsd",
]

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English (original)"
    title = "Zig Programming Language"
    weight = 1
  [languages.it]
    languageName = "Italiano"
    weight = 2
  [languages.pt]
    languageName = "Português"
    weight = 2
  [languages.zh]
    languageName = "简体中文"
    weight = 2
  [languages.de]
    languageName = "Deutsch"
    weight = 2
  [languages.fa]
    languageName = "فارسی"
    weight = 2
  [languages.fr]
    languageName = "Français"
    weight = 2
  [languages.ko]
    languageName = "한국어"
    weight = 2
  [languages.es]
    languageName = "Español"
    weight = 2
  [languages.ar]
    languageName = "عربی"
    weight = 2
  [languages.ru]
    languageName = "Русский"
    title = "Язык программирования Zig"
    weight = 2
