[slogan-latest-release]
other = "Latest Release: &nbsp; <b>{{ . }}</b>"


[back-to-home]
other = "← Back to the <b>Home</b> page"

[back-to-parent]
other = "← Back to the <b>{{ . }}</b> section"


[menu-community]
other = "Join a Community"

[menu-source]
other = "Source Code"


[downloads-heading]
other = "Releases"

[downloads-install-from-pkg-manager]
other = "You can also <a href=\"https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager\"> install Zig from a package manager</a>."

[downloads-json]
other = "There is a <a href=\"https://ziglang.org/download/index.json\">JSON version of this page</a>."

[downloads-minisig]
other = "Files are signed with <a href=\"https://jedisct1.github.io/minisign/\">minisign</a> using this public key:"

[download-binary]
other = "Binary"

[download-documentation]
other = "<a href=\"{{ . }}\">Language Reference</a>"

[download-os]
other = "OS"

[download-arch]
other = "Arch"

[download-filename]
other = "Filename"

[download-sig]
other = "Signature"

[download-kind]
other = "Kind"

[download-release-notes]
other = "<a href=\"{{ . }}\">Release Notes</a>"

[download-size]
other = "Size"

[download-source]
other = "Source"

[download-stdlib-docs]
other = "<a href=\"{{ . }}\">Standard Library Documentation</a>"

[footer-translation]
other = "This page is also available in the following languages"

[news-rss]
other = "This page is also available as an <a href=\"https://ziglang.org/news/index.xml\">RSS feed</a>."
