[slogan-latest-release]
other = "Ultima Versión: &nbsp; <b>{{ . }}</b>"


[back-to-home]
other = "← Volver a <b>Inicio</b>"

[back-to-parent]
other = "← Volver a la sección <b>{{ . }}</b>"


[menu-community]
other = "Unirse a una Comunidad"

[menu-source]
other = "Código Fuente"


[downloads-heading]
other = "Versiones"

[downloads-install-from-pkg-manager]
other = "También puedes <a href=\"https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager\"> instalar Zig desde un manejador de paquetes</a>."

[downloads-json]
other = "Hay una <a href=\"https://ziglang.org/download/index.json\"> versión JSON de esta página</a>."

[download-binary]
other = "Binario"

[download-documentation]
other = "<a href=\"{{ . }}\">Referencia del lenguaje</a>"

[download-filename]
other = "Nombre de archivo"

[download-kind]
other = "Tipo"

[download-release-notes]
other = "<a href=\"{{ . }}\">Notas de la versión</a>"

[download-size]
other = "Tamaño"

[download-source]
other = "Fuentes"

[download-stdlib-docs]
other = "<a href=\"{{ . }}\">Documentación de la Standard Library</a> (experimental)"
